k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: true
    showTime: false
  currentContext: arn:aws:eks:eu-west-1:822793012260:cluster/cln-1-mgmt-k8s-cluster
  currentCluster: arn:aws:eks:eu-west-1:822793012260:cluster/cln-1-mgmt-k8s-cluster
  clusters:
    arn:aws:eks:eu-west-1:151553144567:cluster/crossplane-eks-cluster:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: node
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:151553144567:cluster/swo-cbe-k8s-cluster:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - amazon-cloudwatch
        - fluentbit
        - istio-system
        - external-secrets
        - argocd
        - billing-engine
        - all
        - default
      view:
        active: events
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:822793012260:cluster/cln-1-mgmt-k8s-cluster:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - argocd
        - all
        - default
      view:
        active: ev
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:822793012260:cluster/cln-1-mgmt-k8s-cluster-2:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - external-dns
        - crossplane
        - alb
        - argocd
        - all
        - default
      view:
        active: roles.iam.aws.upbound.io
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/6g/ls182p6d3dbfl7196zbx_zsr0000gn/T/k9s-screens-zen0
