plugin:
  watch-events:
    shortCut: Shift-3
    confirm: false
    description: Get Events
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - "watch -n 5 kubectl get events --context $CONTEXT --namespace $NAMESPACE --field-selector involvedObject.name=$NAME"
  get-crossplane:
    shortCut: Shift-4
    confirm: false
    description: Get crossplane
    scopes:
    - all
    command: kubectl
    background: false
    args:
    - get
    - crossplane
